# Generated by Django 4.2.3 on 2023-07-10 05:07

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(max_length=200)),
                ('class_time', models.DateTimeField(blank=True, null=True)),
                ('class_location', models.CharField(blank=True, max_length=200, null=True)),
                ('exam_time', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid1, editable=False, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
