# Generated by Django 4.2.3 on 2023-07-12 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_course_class_time_alter_course_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='exam_time',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
