# Generated by Django 4.2.3 on 2023-07-31 15:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_course_courses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='courses',
            new_name='profiles',
        ),
    ]
