# Generated by Django 4.2.3 on 2023-08-04 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_ta_tag_profile_assistant_tag'),
        ('courses', '0007_remove_course_profiles_course_studentprofiles_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='taProfiles',
        ),
        migrations.AddField(
            model_name='course',
            name='assistantProfiles',
            field=models.ManyToManyField(blank=True, related_name='assistantCourses', to='users.profile'),
        ),
    ]
