# Generated by Django 4.2.3 on 2023-08-14 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0009_remove_course_assistantprofiles_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
