# Generated by Django 4.2.3 on 2023-08-19 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0010_alter_course_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='group_capacity',
            field=models.IntegerField(default=3),
        ),
        migrations.AddField(
            model_name='course',
            name='projects_phase',
            field=models.IntegerField(default=1),
        ),
    ]
