# Generated by Django 4.2.3 on 2023-08-21 18:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_profile_image'),
        ('courses', '0013_alter_group_creator'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='group',
            unique_together={('course', 'creator')},
        ),
    ]
