# Generated by Django 4.2.3 on 2023-09-09 06:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0017_alter_group_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='projects_phase',
        ),
    ]
