# Generated by Django 4.2.3 on 2023-09-09 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0021_alter_project_project_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='project',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courses.project'),
        ),
    ]
