# Generated by Django 4.2.3 on 2023-09-09 09:40

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_alter_profile_profile_image'),
        ('courses', '0022_alter_course_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadProject',
            fields=[
                ('file', models.FileField(upload_to="projects/student_projects/<class 'str'>")),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.group')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.project')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.profile')),
            ],
            bases=(models.Model, str),
        ),
    ]
