# Generated by Django 4.2.3 on 2023-09-11 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0024_alter_uploadproject_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='project_file',
            field=models.FileField(blank=True, default=None, null=True, upload_to='projects/course_projects/'),
        ),
    ]
