# Generated by Django 4.2.3 on 2023-09-20 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0025_alter_project_project_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='project_uploaded_files_zip',
            field=models.FileField(blank=True, default=None, null=True, upload_to='projects/archives/'),
        ),
    ]
