# Generated by Django 4.2.3 on 2023-09-25 14:10

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0026_project_project_uploaded_files_zip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('period', models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes')])),
                ('coustomـtype', models.BooleanField(default=False)),
                ('number_of_recipints', models.IntegerField()),
                ('status', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('project', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.project')),
            ],
        ),
    ]
