# Generated by Django 4.2.3 on 2023-09-25 14:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0027_schedule'),
    ]

    operations = [
        migrations.CreateModel(
            name='Round',
            fields=[
                ('round_name', models.CharField(blank=True, max_length=250, null=True)),
                ('start_time', models.TimeField()),
                ('finish_time', models.TimeField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('groups', models.ManyToManyField(blank=True, null=True, to='courses.group')),
            ],
        ),
        migrations.AddField(
            model_name='schedule',
            name='rounds',
            field=models.ManyToManyField(blank=True, null=True, to='courses.round'),
        ),
    ]
