# Generated by Django 4.2.3 on 2023-09-25 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0028_round_schedule_rounds'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='groups',
            field=models.ManyToManyField(blank=True, to='courses.group'),
        ),
        migrations.AlterField(
            model_name='schedule',
            name='rounds',
            field=models.ManyToManyField(blank=True, to='courses.round'),
        ),
    ]
