# Generated by Django 4.2.3 on 2023-09-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0029_alter_round_groups_alter_schedule_rounds'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='status',
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.TimeField(choices=[('00:05:00', '5 minutes'), ('00:10:00', '10 minutes'), ('00:15:00', '15 minutes'), ('00:20:00', '20 minutes'), ('00:30:00', '30 minutes')]),
        ),
    ]
