# Generated by Django 4.2.3 on 2023-09-26 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0030_remove_schedule_status_alter_schedule_period'),
    ]

    operations = [
        migrations.RenameField(
            model_name='schedule',
            old_name='coustomـtype',
            new_name='customـtype',
        ),
    ]
