# Generated by Django 4.2.3 on 2023-09-27 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0032_alter_schedule_period'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='round',
            options={'ordering': ['start_time']},
        ),
        migrations.AlterField(
            model_name='schedule',
            name='period',
            field=models.IntegerField(choices=[(5, '5 minutes'), (10, '10 minutes'), (15, '15 minutes'), (20, '20 minutes'), (30, '30 minutes')]),
        ),
    ]
