# Generated by Django 4.2.3 on 2023-09-30 17:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0033_alter_round_options_alter_schedule_period'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='customـtype',
        ),
    ]
