# Generated by Django 4.2.3 on 2023-08-04 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_profile_profile_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='ta_tag',
            new_name='assistant_tag',
        ),
    ]
