# Generated by Django 4.2.3 on 2023-08-05 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_rename_ta_tag_profile_assistant_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='default_profile', upload_to='images/profiles/'),
        ),
    ]
