# Generated by Django 4.2.3 on 2023-08-08 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_profile_assistant_tag_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/default_profile', upload_to='images/profiles/'),
        ),
    ]
