# Generated by Django 4.2.3 on 2023-08-08 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_alter_profile_profile_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(default='images/profiles/default_profile.png', upload_to='images/profiles/'),
        ),
    ]
