# Generated by Django 4.2.3 on 2023-08-14 13:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_profile_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='status',
        ),
    ]
