# Generated by Django 4.2.3 on 2023-08-16 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_remove_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='bio',
            field=models.CharField(blank=True, default='سلام، من یک کاربر سامانه تام هستم', max_length=400, null=True),
        ),
    ]
