# Generated by Django 4.2.3 on 2023-08-16 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_profile_bio'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='national_id',
        ),
        migrations.AlterField(
            model_name='profile',
            name='id',
            field=models.CharField(editable=False, max_length=16, primary_key=True, serialize=False, unique=True),
        ),
    ]
