# Generated by Django 4.2.3 on 2023-08-20 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_profile_national_id_alter_profile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_image',
            field=models.ImageField(blank=True, default='images/profiles/default_profile.png', null=True, upload_to='images/profiles/'),
        ),
    ]
